# Generated by Django 4.2.16 on 2025-08-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usermetadata_drives_remove_usermetadata_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermetadata',
            name='age',
        ),
        migrations.RemoveField(
            model_name='usermetadata',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='usermetadata',
            name='location',
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='drives',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='interests',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
