# Generated by Django 4.2.16 on 2025-08-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usermetadata_age_remove_usermetadata_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetadata',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
